# Generated by Django 6.0.4 on 2026-05-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mnc", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="progress",
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
